version: '3'
services:
  crm-app:
    image: djcrm:1
    container_name: crm-app
    environment:
      - DBNAME=crm
      - DBUSER=crm
      - DBPASSWORD=crm
      - DBHOST=crm-db
      - DBPORT=5432
      - ENV_TYPE=development
      - DEFAULT_FROM_EMAIL=your_email@example.com
      - ADMIN_EMAIL=your_admin_email@example.com
      - CELERY_BROKER_URL="celery.url"
      - CELERY_RESULT_BACKEND="celery.backend.url"
      - DOMAIN_NAME="DOMAIN.NAME"
      - SWAGGER_ROOT_URL="SWAGGER.ROOT.URL"
    depends_on:
      - crm-db
    ports:
      - 8000:8000
    networks:
      - nw

  crm-db:
    image: postgres:12-bookworm
    container_name: crm-db
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=crm
      - POSTGRES_PASSWORD=crm
    ports:
      - 5432:5432
    volumes:
      - ./db-volume/:/var/run/postgresql
    networks:
      - nw

networks:
  nw: {}
